shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'


urlpatterns = [
    path('add/', views.cart_add, name='cart_add'),
    path('summary/', views.cart_summary, name='cart_summary'),
    path('update', views.cart_update, name='cart_update'),
    path('delete', views.cart_delete, name='cart_delete'),
    
]

shop/core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug_category>', views.category, name='category'),
    path('product/<slug:slug_product>', views.product_detail, name='product_detail'),
    path('session/', views.session, name='session'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete/', views.complete_order, name='complete_order'),
    path('history/', views.history_list, name='history'),
    path('order_detail/<int:id>', views.order_detail, name='order_detail'),
    
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/core/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from user.models import UserBase

class Category(models.Model):
    name = models.CharField(max_length=250, db_index=True)
    image_banner = models.ImageField(upload_to='images/', blank=True, null=True)
    image_index = models.ImageField(upload_to='images/', blank=True, null=True)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        verbose_name_plural = 'categories' 

    def get_absolute_url(self):
        return reverse('core:category', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=250, db_index=True)
    slug = models.SlugField(max_length=250, unique=True)

    

    def get_absolute_url(self):
        return reverse('core:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=250, db_index=True)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    price = models.IntegerField()
    slug = models.SlugField(max_length=250, unique=True, blank=True)
    on_stock = models.IntegerField(default=5)
    image = models.ImageField(upload_to='images/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, on_delete= models.CASCADE)
    product_code = models.CharField(max_length=120)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name + "-" + self.product_code)
        super(Product, self).save(*args, **kwargs)
        
    def get_absolute_url(self):
        return reverse('core:product_detail', args=[self.slug])
    
class Order(models.Model):
    user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    order_price = models.IntegerField()
    no_of_items = models.IntegerField()
    
    def get_absolute_url(self):
        return reverse("core:order_detail", args=[self.id])
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    item_price = models.IntegerField()
    total_price = models.IntegerField()

shop/core/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.sessions.models import Session
from django.http import HttpResponse

from .models import Category, Product, Brand, Order, OrderItem
from cart.cart import Cart, CartAuth
from .order_history import OrderManager

# context processors

def category_list(request):
    return {'category_list': Category.objects.all()}

#------------------------------------------------------------------



def index(request):
    user = request.user
    best_sellers = Product.objects.all()
    context = {'user':user, 'best_sellers':best_sellers}
    return render(request, 'core/index.html', context)

# Overview of single category with all products
def category(request, slug_category):
    category = get_object_or_404(Category, slug=slug_category)
    products = Product.objects.filter(category=category)
    brands = Brand.objects.all()
    context = {'category':category, 'products':products, 'brands':brands}
    return render(request, 'core/category.html', context)


#Detail of selected product (description, price, availability, pictures....)
def product_detail(request, slug_product):
    product = get_object_or_404(Product, slug=slug_product)
    context = {'product':product}
    
    return render(request, 'core/detail.html', context)


#Final overview of the order.
def checkout(request):
    cart = Cart(request)
    context = {'cart':cart}
    return render(request, 'core/checkout.html', context)


#Finishes the order and saves the order in history if user is signed in
def complete_order(request):
    if request.user.is_authenticated:
        manager = OrderManager(request)
        manager.archive_current_order()
    cart = Cart(request)
    cart.delete_cart()
    if request.user.is_authenticated:
        cart_auth = CartAuth(request)
        cart_auth.delete_cart_auth()
    return render(request,'core/complete_order.html')


#Shows all orders made by user
def history_list(request):
    orders = Order.objects.filter(user=request.user)
    context = {'orders':orders}
    return render(request, 'core/history_list.html', context)


#Details of a single order from history
def order_detail(request, id):
    manager = OrderManager(request)
    items = manager.get_order_detail(id)
    subtotal = manager.get_order_price(id)
    context = {'items':items, 'subtotal':subtotal}
    print(items[0].values())
    return render(request, 'core/order_detail.html', context)

shop/templates/core/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Category{% endblock title %}


{% block content %}




<!--Plugin CSS file with desired skin-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>

<!--jQuery-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--Plugin JavaScript file-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>   
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>aranoz</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <!-- nice select CSS -->
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">



   

    <!--================Home Banner Area =================-->
    <!-- breadcrumb start-->
    <style>
        .breadcrumb_bg{background-image:url('{{category.image_banner.url}}');
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;}
    </style>
    <section class="breadcrumb breadcrumb_bg">
      
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Shop {{category.name}}</h2>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================Category Product Area =================-->
    <section class="cat_product_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="left_sidebar_area">
                        

                       

                        

                        
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product_top_bar d-flex justify-content-between align-items-center">
                                <div class="single_product_menu">
                                    
                                </div>
                               
                                <div class="single_product_menu d-flex">
                                   
                                </div>
                                <div class="single_product_menu d-flex">
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row align-items-center latest_product_inner">
                        {% for product in products %}
                        
                        <div class="col-lg-4 col-sm-6">
                           
                            <div class="single_product_item">
                                <img src="{{product.image.url}}" alt="" style="height:350px;">
                                <div class="single_product_text">
                                    <h4>{{product.brand}}  {{product.name}}</h4>
                                    <h3><div value="{{product.price}}" class="product-price" id="product-price{{product.product_code}}" data-index="{{product.product_code}}">{{product.price}}</div> CZK</h3>
                                    <a href="{{ product.get_absolute_url }}" class="add_cart">Detail</a>
                                </div>
                            </div>
                            
                        </div>
                        {% endfor %}
                       
                       
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Category Product Area =================-->

   

   

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/stellar.js' %}"></script>
    <script src="{% static 'js/price_rangs.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
 

    {% endblock content %}

shop/templates/core/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}

{% block content %}

  <!--================Checkout Area =================-->
  <section class="checkout_area padding_top">
    <div class="container">
     
      
      <div class="billing_details">
        <div class="row">
          <div class="col-lg-8">
            <h3>Billing Details</h3>
            <form class="row contact_form" action="#" method="post" novalidate="novalidate">
              <div class="col-md-6 form-group p_star">
                <input type="text" class="form-control" id="first" name="name" />
                <span class="placeholder" data-placeholder="First name"></span>
              </div>
              <div class="col-md-6 form-group p_star">
                <input type="text" class="form-control" id="last" name="name" />
                <span class="placeholder" data-placeholder="Last name"></span>
              </div>
              <div class="col-md-12 form-group">
                <input type="text" class="form-control" id="company" name="company" placeholder="Company name" />
              </div>
              <div class="col-md-6 form-group p_star">
                <input type="text" class="form-control" id="number" name="number" />
                <span class="placeholder" data-placeholder="Phone number"></span>
              </div>
              <div class="col-md-6 form-group p_star">
                <input type="text" class="form-control" id="email" name="compemailany" />
                <span class="placeholder" data-placeholder="Email Address"></span>
              </div>
              
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="add1" name="add1" />
                <span class="placeholder" data-placeholder="Address line 01"></span>
              </div>
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="add2" name="add2" />
                <span class="placeholder" data-placeholder="Address line 02"></span>
              </div>
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="city" name="city" />
                <span class="placeholder" data-placeholder="Town/City"></span>
              </div>
              
              <div class="col-md-12 form-group">
                <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP" />
              </div>
              <div class="col-md-12 form-group">
               
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account">
                  <h3>Shipping Details</h3>
                  <input type="checkbox" id="f-option3" name="selector" />
                  <label for="f-option3">Ship to a different address?</label>
                </div>
                <textarea class="form-control" name="message" id="message" rows="1"
                  placeholder="Order Notes"></textarea>
              </div>
            </form>
          </div>
          <div class="col-lg-4">
            <div class="order_box">
              <h2>Your Order</h2>
              <ul class="list">
                <li>
                  <a href="#">Product
                    <span>Total</span>
                  </a>
                </li>
                {% for item in cart %}
                <li>
                  <a href="#">{{item.product.brand.name}} {{item.product.name}}
                    <span class="middle">x {{item.quantity}}</span>
                    <span class="last">CZK {{item.item_sum_price}}</span>
                  </a>
                </li>
                {% endfor %}
               
              </ul>
              <ul class="list list_2">
                
                
                <li>
                  <a href="#">Total
                    <span>CZK {{cart.cart_subtotal}}</span>
                  </a>
                </li>
              </ul>
              <div class="payment_item">
                <div class="radion_btn">
                  <input type="radio" id="f-option5" name="selector" />
                  <label for="f-option5">Check payments</label>
                  <div class="check"></div>
                </div>
                <p>
                  Please send a check to Store Name, Store Street, Store Town,
                  Store State / County, Store Postcode.
                </p>
              </div>
              <div class="payment_item active">
                <div class="radion_btn">
                  <input type="radio" id="f-option6" name="selector" />
                  <label for="f-option6">Paypal </label>
                  <img src="img/product/single-product/card.jpg" alt="" />
                  <div class="check"></div>
                </div>
                <p>
                  Please send a check to Store Name, Store Street, Store Town,
                  Store State / County, Store Postcode.
                </p>
              </div>
              <div class="creat_account">
                <input type="checkbox" id="f-option4" name="selector" />
                <label for="f-option4">I’ve read and accept the </label>
                <a href="#">terms & conditions*</a>
              </div>
              <a class="btn_3" href="{% url 'core:complete_order' %}">Proceed</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Checkout Area =================-->

  {% endblock content %}

  

shop/templates/core/complete_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Completed{% endblock title %}

{% block content %}
<section class="checkout_area padding_top">
  <div class="container">
   
    <div><h1>Your order has been completed!</h1></div>
    
  </div>
</section>



{% endblock content %}

  

shop/templates/core/detail.html
  {% extends 'base.html' %}
  {% load static %}
  
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>aranoz</title>
  <link rel="icon" href="img/favicon.png">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- animate CSS -->
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <!-- owl carousel CSS -->
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/lightslider.min.css' %}">
  <!-- font awesome CSS -->
  <link rel="stylesheet" href="{% static 'css/all.css' %}">
  <!-- flaticon CSS -->
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  <!-- font awesome CSS -->
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <!-- style CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block title %}{{product.name}}{% endblock title %}

 
{% block content %}
 

  <!--================Single Product Area =================-->
  <div class="product_image_area section_padding">
    <div class="container">
      <div class="row s_product_inner justify-content-between">
        <div class="col-lg-7 col-xl-7">
          <div class="product_slider_img">
            <div id="vertical">
              <div data-thumb="img/product/single-product/product_1.png">
                <img src="{{product.image.url}}" />
              </div>
             
            </div>
          </div>
        </div>
        <div class="col-lg-5 col-xl-4">
          <div class="s_product_text">
     
            <h3>{{product.brand}}  {{product.name}}</h3>
            <h2>CZK {{product.price}}</h2>
            <ul class="list">
              <li>
                <a class="active" href="{{product.category.get_absolute_url}}">
                  <span>Category</span>{{product.category}}</a>
              </li>
              <li>
                <a href="#"> <span>Availibility</span>{{product.on_stock}}</a>
              </li>
            </ul>
            <p>
              {{product.description}}
            </p>
            <div class="card_area d-flex justify-content-between align-items-center">
              <div class="product_count">
                
                <input class="input-number" id="quantity_id" type="text" value="1" min="0" max="10">
              
              </div>
              <button type="button" id="add-button" class="btn_3" value="{{product.product_code}}">add to cart</button>
      
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--================End Single Product Area =================-->

  <!--================Product Description Area =================-->
 



  <!-- jquery plugins here-->
  <!-- jquery -->
  <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- easing js -->
  <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
  <!-- swiper js -->
  <script src="{% static 'js/lightslider.min.js' %}"></script>
  <!-- swiper js -->
  <script src="{% static 'js/masonry.pkgd.js' %}"></script>
  <!-- particles js -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
  <!-- slick js -->
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/swiper.jquery.js' %}"></script>
  <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <script src="{% static 'js/contact.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'js/jquery.form.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'js/mail-script.js' %}"></script>
  <script src="{% static 'js/stellar.js' %}"></script>
  <!-- custom js -->
  <script src="{% static 'js/theme.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  <script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                code: $('#add-button').val(),
                quantity: $('#quantity_id').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("cart-products").innerHTML = json.no_of_products
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock content %}

shop/templates/core/history_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}History{% endblock title %}




{% block content %}
  <!--================Cart Area =================-->
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Price</th>
                <th scope="col">No. of items</th>
              </tr>
            </thead>
            <tbody id="cart-summary">
              
              {% for order in orders %}
            
              <tr class="cart-item{{item.product.product_code}}">
                
                <td>
                  <a href="{{order.get_absolute_url}}">
                  <div class="media">
                    <div class="media-body">
                      <p>{{ order.created }}</p>
                    </div>
                  </div>
                </a>
                </td>
              
                <td>
                  <div>
                    CZK<h5>{{ order.order_price }}</h5>
                  </div>
                </td>
                <td>
                  <div class="product_count">
                   {{order.no_of_items}}
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
  </section>
  <!--================End Cart Area =================-->


  {% endblock content %}

shop/templates/core/index.html
    {% extends 'base.html' %}
    {% load static %}
    {% block title %}Home{% endblock title %}
    {% block content %}

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="banner_slider owl-carousel">
                        {% for category in category_list %}
                        <div class="single_banner_slider">
                            <div class="row">
                                <div class="col-lg-5 col-md-8">
                                    <div class="banner_text">
                                        <div class="banner_text_iner">
                                            <h1>{{category.name}}</h1>
                                            <p>Incididunt ut labore et dolore magna aliqua quis ipsum
                                                suspendisse ultrices gravida. Risus commodo viverra</p>
                                            <a href="{{category.get_absolute_url}}" class="btn_2">buy now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="banner_img d-none d-lg-block">
                                    <img src="{{category.image_index.url}}" alt="">
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                        <!-- <div class="single_banner_slider">
                            <div class="row">
                                <div class="col-lg-5 col-md-8">
                                    <div class="banner_text">
                                        <div class="banner_text_iner">
                                            <h1>Cloth $ Wood Sofa</h1>
                                            <p>Incididunt ut labore et dolore magna aliqua quis ipsum
                                                suspendisse ultrices gravida. Risus commodo viverra</p>
                                            <a href="#" class="btn_2">buy now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="banner_img d-none d-lg-block">
                                    <img src="img/banner_img.png" alt="">
                                </div>
                            </div>
                        </div> -->
                    </div>
                    
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

    

  

    

    <!-- product_list part start-->
    <section class="product_list best_seller section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="section_tittle text-center">
                        <h2>Best Sellers <span>shop</span></h2>
                    </div>
                </div>
            </div>
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-12">
                    <div class="best_product_slider owl-carousel">
                        {% for product in best_sellers %}
                        <div class="col-lg-4 col-sm-6">
                           
                            <div class="single_product_item">
                                <img src="{{product.image.url}}" alt="" style="height:170px;">
                                <div class="single_product_text">
                                    <h4>{{product.brand}}  {{product.name}}</h4>
                                    <h3><div value="{{product.price}}" class="product-price" id="product-price{{product.product_code}}" data-index="{{product.product_code}}">{{product.price}}</div> CZK</h3>
                                    <a href="{{ product.get_absolute_url }}" class="add_cart">Detail</a>
                                </div>
                            </div>
                            
                        </div>
                        {% endfor %}
                       
                       
                       
                       
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product_list part end-->

   

    <!-- subscribe_area part start-->
    <section class="client_logo padding_top">
        <div class="container">
            <div class="row align-items-center"></div>
            </div>
        </div>
    </section>
    <!--::subscribe_area part end::-->

    {% endblock content %}
   