shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'


urlpatterns = [
    path('add/', views.cart_add, name='cart_add'),
    path('summary/', views.cart_summary, name='cart_summary'),
    path('update', views.cart_update, name='cart_update'),
    path('delete', views.cart_delete, name='cart_delete'),
    
]

shop/core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug_category>', views.category, name='category'),
    path('product/<slug:slug_product>', views.product_detail, name='product_detail'),
    path('session/', views.session, name='session'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete/', views.complete_order, name='complete_order'),
    path('history/', views.history_list, name='history'),
    path('order_detail/<int:id>', views.order_detail, name='order_detail'),
    
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

from user.models import UserBase
from core.models import Product


#Cart is stored in databse for loged in user
class CartModel(models.Model):
    user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    
class CartItem(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    
    

shop/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from core.models import Product
from .cart import Cart, CartAuth

# context processors
def cart(request):
    cart = Cart(request)
    return {'cart':cart}
#------------------------------------------
    
#Add selected product in session and also in database, if user is logged in. 
#Product needs to be added in session in both cases, because cart template loads data from session 
def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_code = request.POST.get('code')
        quantity = int(request.POST.get('quantity'))
        cart.cart_add_product(code=product_code, quantity=quantity)
        no_of_products = str(cart.__len__())
        response = JsonResponse({'no_of_products':no_of_products, "success":True})
        if request.user.is_authenticated:
            cart_auth = CartAuth(request)
            cart_auth.cart_auth_add(code=product_code, quantity=quantity)
       
        return response
 
 
#Overview of all products in cart    
def cart_summary(request):
    cart = Cart(request)
    subtotal = cart.cart_subtotal()
    context = {'subtotal':subtotal}
    return render(request, 'cart/cart.html', context)


#Updates cart if quantity of a product is changed
def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_code = request.POST.get('productcode')
        quantity = int(request.POST.get('productqty'))
        cart.update_item(code=product_code, quantity=quantity)
        new_item_price = cart.get_item_price(code=product_code)
        subtotal = cart.cart_subtotal()
        if request.user.is_authenticated:
            cart_auth = CartAuth(request)
            cart_auth.cart_auth_update(code=product_code, quantity=quantity)
        no_of_products = str(cart.__len__())
        response = JsonResponse({'item_total':new_item_price, 'subtotal':subtotal, 'no_of_products':no_of_products, "success":True})
        return response

#Updates cart if a product is deleted    
def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_code = request.POST.get('productcode')
        cart.delete_item(product_code)
        subtotal = cart.cart_subtotal()
        no_of_products = str(cart.__len__())
        if request.user.is_authenticated:
            cart_auth = CartAuth(request)
            cart_auth.cart_auth_delete(product_code)
        response = JsonResponse({'subtotal':subtotal, 'no_of_products':no_of_products, "success":True})
        return response
        
        
    
    

    

shop/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}




{% block content %}
  

  <style>
    .img-cart{
      height:100px;
    }

    .delete-button{
      border:none;
      background-color:white;
    }

  

  </style> 

  <!--================Cart Area =================-->
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody id="cart-summary">
              
              {% for item in cart %}
              
              <tr class="cart-item{{item.product.product_code}}">
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="{{ item.product.image.url }}" alt="" class="img-cart" />
                    </div>
                    <div class="media-body">
                      <p>{{ item.product.name }}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <div>
                    CZK<h5>{{ item.product.price }}</h5>
                  </div>
                </td>
                <td>
                  <div class="product_count">
                   
                   
                    <input class="input-number" id="qty{{item.product.product_code}}" data-index="{{item.product.product_code}}" type="text" value="{{ item.quantity }}" min="0" max="10">
                   
                  </div>
                </td>
                <td>
                  CZK<h5 id="item-total{{item.product.product_code}}">{{ item.item_sum_price }}</h5>
                </td>
                <td>
                  <button id="delete-button" class="delete-button" type="button" data-index="{{item.product.product_code}}">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
                </td>
              </tr>
              
              
              {% endfor %}
              
              <tr class="bottom_button">
               
               
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5>Subtotal</h5>
                </td>
                <td style="display:block;">
                  <h5>CZK<div id="subtotal">{{ subtotal }}</div></h5>
                </td>
              
              </tr>
             
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="{% url 'core:index' %}">Continue Shopping</a>
            <a class="btn_1 checkout_btn_1" href="{% url 'core:checkout' %}">Proceed to checkout</a>
          </div>
        </div>
      </div>
  </section>
  <!--================End Cart Area =================-->

 


  <script>
    
      $(document).on('change', '.input-number', function () {
        var prodcode = $(this).data('index');
        $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_update" %}',
          data: {
            productcode: $(this).data('index'),
            productqty: $('#qty'+ prodcode).val(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
          
          },
          success: function (json) {
            
            document.getElementById("subtotal").innerHTML = json.subtotal,
            document.getElementById("item-total" + prodcode).innerHTML = json.item_total,
            document.getElementById("cart-products").innerHTML = json.no_of_products
          },
          error: function (xhr, errmsg, err) {}
          
        });
      })

      $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodcode = $(this).data('index');
        $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_delete" %}',
          data: {
            productcode: $(this).data('index'),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
          
          },
          success: function (json) {
            console.log(prodcode)
            $('.cart-item' + prodcode).remove();
            document.getElementById("subtotal").innerHTML = json.subtotal,
            document.getElementById("cart-products").innerHTML = json.no_of_products
          },
          error: function (xhr, errmsg, err) {}
          
        });
      })
    
  
  
  </script>


 
 

  {% endblock content %}