shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'


urlpatterns = [
    path('add/', views.cart_add, name='cart_add'),
    path('summary/', views.cart_summary, name='cart_summary'),
    path('update', views.cart_update, name='cart_update'),
    path('delete', views.cart_delete, name='cart_delete'),
    
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'user'


urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="core:index"), name='logout'),
    path('register-success/', views.register_success, name='register_success'),
    path('load_cart/', views.LoadCart.as_view(), name='load_cart'),
   
]

shop/user/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.db import models


class CustomAccountManager(BaseUserManager):
    
    def create_superuser(self, email, user_name, password, **other_fields):
        
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        
        if other_fields.get('is_staff') is not True:
            raise ValueError('User is not staff')

        return self.create_user(email, user_name, password, **other_fields)
    
    def create_user(self, email, user_name, password, **other_fields):
        
        if not email:
            raise ValueError(_('E-mail'))
            
        
        email = self.normalize_email(email)
        user = self.model(email=email, user_name=user_name, **other_fields)
        user.set_password(password)
        user.save()
        return user
        

class UserBase(AbstractBaseUser, PermissionsMixin):
    
    email = models.EmailField(_('E-mail'), unique=True)
    user_name = models.CharField(max_length=150, unique=True)
    phone_number = models.CharField(max_length=15, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = CustomAccountManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
    
    def __str__(self):
        return self.user_name
    
    

    
    
    

shop/user/forms.py
from django import forms
from .models import UserBase
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate

class RegistrationForm(forms.ModelForm):
    
    user_name = forms.CharField(
        label='Username', min_length=4, max_length=50, help_text='Required'
    )
    email = forms.EmailField(label="E-mail", max_length=100, help_text='Required', error_messages={'required':'E-mail required'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Validation', widget=forms.PasswordInput)
    
    class Meta:
        model = UserBase
        fields = ('user_name', 'email',)
        
    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Passwords do not match!!')
        return data['password2']
    
class LoginForm(AuthenticationForm):   
    username = forms.CharField(label='E-mail', max_length=150, widget=forms.TextInput, error_messages={'required': 'E-mail is required'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=150, error_messages={'required': 'Password is required'})
    
   
    
    
   

shop/user/views.py
from .forms import RegistrationForm, LoginForm
from cart.cart import Cart, CartAuth

from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth import views as auth_views
from django.views import View
from django.http import HttpResponseRedirect
from django.urls import reverse


def register_user(request):
    
    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.save()
            return redirect('user:register_success')
            
            
    else:
        registerForm = RegistrationForm()
    return render(request, 'user/register.html', {'form': registerForm})

def register_success(request):
    return render(request,'user/register_success.html')


class Login(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'user/login.html'
    success_url = 'user:load_cart'
    
    
    
#Loads items in cart from database,if the user was previously loged in and add something in cart    
class LoadCart(View):
    def get(self, request):
        cart = Cart(request)
        cart.cart_load_from_db()
        return HttpResponseRedirect(reverse('core:index'))
   
       
       
   
   
   
   
        
        
        

            
            
            
            
           

    

shop/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block content %}


   

    <!--================login_part Area =================-->
    <section class="login_part padding_top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_text text-center">
                        <div class="login_part_text_iner">
                            <h2>New to our Shop?</h2>
                            <p>There are advances being made in science and technology
                                everyday, and a good example of this is the</p>
                            <a href="{% url 'user:register' %}" class="btn_3">Create an Account</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>Welcome Back ! <br>
                                Please Sign in now</h3>
                                
                            <form class="row contact_form" action="" method="post">
                                {% csrf_token %}  
                                <h3 style="color:red;">{{form.non_field_errors}}</h3>                            
                                {% for field in form %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <h3 style="color:red;">{{error}}</h1>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                                
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" name="username"
                                        placeholder="E-mail">
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control"  name="password"
                                        placeholder="Password">
                                </div>
                                <div class="col-md-12 form-group">
                                   
                                    <button type="submit" value="submit" class="btn_3">
                                        log in
                                    </button>
                                    
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->

{% endblock content %}

    

shop/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register{% endblock title %}

{% block content %}
   

   


   
    <!-- breadcrumb start-->

    <!--================login_part Area =================-->
    <section class="login_part padding_top">
        <div class="container">
            <div class="row align-items-center">
               
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>Register</h3>
                            <form class="row contact_form" action="." method="post">
                                {% csrf_token %}
                                {% if form.errors %}
                                {% for field in form %}
                                {% if field.errors %}
                                <h3 style="color:red;">{{ field.label }}: {{field.errors|striptags}}</h1>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                               
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" name="user_name" value=""
                                        placeholder="{{form.user_name.label}}">
                                </div>

                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" name="email" value=""
                                        placeholder="{{form.email.label}}">
                                </div>

                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control" name="password" value=""
                                        placeholder="{{form.password.label}}">
                                </div>

                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control" name="password2" value=""
                                        placeholder="{{form.password2.label}}">
                                </div>

                                
                                <div class="col-md-12 form-group">
                                   
                                    <button type="submit" value="submit" class="btn_3">
                                        Submit
                                    </button>
                                    <a class="lost_pass" href="{% url 'user:login' %}">Already have account? Login</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->

    

   

{% endblock content %}

shop/templates/user/register_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Successful registration{% endblock title %}

{% block content %}


   

    <!--================login_part Area =================-->
    <section class="login_part padding_top">
        <div class="container">
            <div class="row align-items-center">
                
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>Successfully registered ! <br>
                                Please Sign in now</h3>
                            
                                   
                                    <a href="{% url 'user:login' %}" type="button"  class="btn_3">
                                        log in
                                    </a>
                                    
                              
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->

{% endblock content %}

    